Repository Leets-Official/Weeth-BE, pull requests merged in 2024-07, with the labels that each got.

#3 Feat: 로그인 및 회원가입 구현
  .gitignore
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/dependencies-accessors/gc.properties
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileChanges/last-build.bin
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/8.8/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/gradle.xml
  build.gradle
  build/classes/java/main/leets/weeth/WeethApplication.class
  build/resources/main/application-local.yml
  build/resources/main/application-prod.yml
  build/resources/main/application.yml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/leets/weeth/WeethApplication.java
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/entity/enums/Role.java
  src/main/java/leets/weeth/domain/user/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/leets/weeth/global/auth/jwt/service/JwtService.java
  src/main/java/leets/weeth/global/auth/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/leets/weeth/global/auth/login/handler/LoginFailureHandler.java
  src/main/java/leets/weeth/global/auth/login/handler/LoginSuccessHandler.java
  src/main/java/leets/weeth/global/auth/login/service/LoginService.java
  src/main/java/leets/weeth/global/common/entity/BaseEntity.java
  src/main/java/leets/weeth/global/common/exception/BusinessLogicException.java
  src/main/java/leets/weeth/global/common/exception/CommonExceptionController.java
  src/main/java/leets/weeth/global/common/exception/ExceptionType.java
  src/main/java/leets/weeth/global/common/response/CommonResponse.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
Labels: Feature

#10 #9 Refactor: 회원 가입 기능 및 OB 지원 기능
  build.gradle
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/converter/CardinalListConverter.java
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/entity/enums/Department.java
  src/main/java/leets/weeth/domain/user/entity/enums/Position.java
  src/main/java/leets/weeth/domain/user/entity/enums/Status.java
  src/main/java/leets/weeth/domain/user/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
Labels: Feature, Refactor

#14 #13 Feature: 일정 관련 로직 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/leets/weeth/domain/event/controller/EventController.java
  src/main/java/leets/weeth/domain/event/dto/RequestEvent.java
  src/main/java/leets/weeth/domain/event/dto/ResponseEvent.java
  src/main/java/leets/weeth/domain/event/entity/Event.java
  src/main/java/leets/weeth/domain/event/entity/enums/ErrorMessage.java
  src/main/java/leets/weeth/domain/event/entity/enums/ResponseMessage.java
  src/main/java/leets/weeth/domain/event/mapper/EventMapper.java
  src/main/java/leets/weeth/domain/event/repository/EventRepository.java
  src/main/java/leets/weeth/domain/event/service/EventService.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
  src/main/java/leets/weeth/global/config/SwaggerConfig.java
Labels: Feature

#18 #16 feat: 일정 - 유저 관계 매핑 및 일부 로직 수정
  src/main/java/leets/weeth/domain/event/controller/EventController.java
  src/main/java/leets/weeth/domain/event/dto/RequestEvent.java
  src/main/java/leets/weeth/domain/event/dto/ResponseEvent.java
  src/main/java/leets/weeth/domain/event/entity/Event.java
  src/main/java/leets/weeth/domain/event/entity/enums/ErrorMessage.java
  src/main/java/leets/weeth/domain/event/mapper/EventMapper.java
  src/main/java/leets/weeth/domain/event/repository/EventRepository.java
  src/main/java/leets/weeth/domain/event/service/EventService.java
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/common/error/CommonExceptionController.java
  src/main/java/leets/weeth/global/common/error/exception/ExceptionType.java
  src/main/java/leets/weeth/global/common/error/exception/custom/BusinessLogicException.java
  src/main/resources/application.yml
Labels: Feature

#25 Refactor #22
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/auth/annotation/CurrentUser.java
  src/main/java/leets/weeth/global/auth/jwt/service/JwtService.java
  src/main/java/leets/weeth/global/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/leets/weeth/global/config/WebMvcConfig.java
Labels: Refactor

#28 Feature-#26
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/common/error/exception/custom/EmailExistsException.java
  src/main/java/leets/weeth/global/common/error/exception/custom/InvalidAccessException.java
  src/main/java/leets/weeth/global/common/error/exception/custom/UserNotFoundException.java
Labels: Feature, Refactor

#29 Refactor-#24
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/repository/UserRepository.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/common/error/exception/custom/EmailExistsException.java
  src/main/java/leets/weeth/global/common/error/exception/custom/UserExistsException.java
Labels: Feature, Refactor

#33 #32 Feat: 회원 수정
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
Labels: Feature

#17 #6 Feat: 게시글 구현
  .idea/modules.xml
  build.gradle
  src/main/java/leets/weeth/domain/file/entity/File.java
  src/main/java/leets/weeth/domain/file/repository/FileRepository.java
  src/main/java/leets/weeth/domain/file/service/FileService.java
  src/main/java/leets/weeth/domain/post/controller/CommentController.java
  src/main/java/leets/weeth/domain/post/controller/PostController.java
  src/main/java/leets/weeth/domain/post/dto/RequestCommentDTO.java
  src/main/java/leets/weeth/domain/post/dto/RequestPostDTO.java
  src/main/java/leets/weeth/domain/post/dto/ResponseCommentDTO.java
  src/main/java/leets/weeth/domain/post/dto/ResponsePostDTO.java
  src/main/java/leets/weeth/domain/post/entity/Comment.java
  src/main/java/leets/weeth/domain/post/entity/Post.java
  src/main/java/leets/weeth/domain/post/repository/CommentRepository.java
  src/main/java/leets/weeth/domain/post/repository/PostRepository.java
  src/main/java/leets/weeth/domain/post/service/CommentService.java
  src/main/java/leets/weeth/domain/post/service/PostService.java
  src/main/java/leets/weeth/global/common/error/exception/custom/PostNotFoundException.java
  src/main/java/leets/weeth/global/config/AwsS3Config.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Feature

#41 #40 Feat: 공지사항에 파일 첨부 기능 추가
  src/main/java/leets/weeth/domain/event/controller/EventController.java
  src/main/java/leets/weeth/domain/event/dto/ResponseEvent.java
  src/main/java/leets/weeth/domain/event/entity/Event.java
  src/main/java/leets/weeth/domain/event/mapper/EventMapper.java
  src/main/java/leets/weeth/domain/event/service/EventService.java
  src/main/java/leets/weeth/domain/notice/controller/NoticeController.java
  src/main/java/leets/weeth/domain/notice/dto/ResponseNotice.java
  src/main/java/leets/weeth/domain/notice/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/notice/service/NoticeService.java
Labels: Feature, Refactor

#37 #36 Feat: 댓글 기능
  src/main/java/leets/weeth/domain/post/controller/CommentController.java
  src/main/java/leets/weeth/domain/post/dto/RequestCommentDTO.java
  src/main/java/leets/weeth/domain/post/dto/ResponseCommentDTO.java
  src/main/java/leets/weeth/domain/post/dto/ResponsePostDTO.java
  src/main/java/leets/weeth/domain/post/entity/Comment.java
  src/main/java/leets/weeth/domain/post/entity/Post.java
  src/main/java/leets/weeth/domain/post/repository/CommentRepository.java
  src/main/java/leets/weeth/domain/post/service/CommentService.java
  src/main/java/leets/weeth/domain/post/service/PostService.java
  src/main/java/leets/weeth/global/common/error/exception/custom/CommentNotFoundException.java
Labels: Feature

#39 #38 Fix: 유저 정보 수정 로직 오류
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/common/error/exception/ExceptionType.java
Labels: bug

#47 #46 Feat: 유저 가입 신청 승인
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
Labels: Feature

#49 #48 Feat: 유저 도메인 어드민 컨트롤러
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/entity/enums/Role.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
  src/main/java/leets/weeth/global/config/SecurityConfig.java
Labels: Feature

#52 #51 Feat: 회비 관련 API
  src/main/java/leets/weeth/domain/account/controller/AccountController.java
  src/main/java/leets/weeth/domain/account/dto/AccountDTO.java
  src/main/java/leets/weeth/domain/account/dto/ReceiptDTO.java
  src/main/java/leets/weeth/domain/account/entity/Account.java
  src/main/java/leets/weeth/domain/account/entity/Receipt.java
  src/main/java/leets/weeth/domain/account/mapper/AccountMapper.java
  src/main/java/leets/weeth/domain/account/mapper/ReceiptMapper.java
  src/main/java/leets/weeth/domain/account/repository/AccountRepository.java
  src/main/java/leets/weeth/domain/account/repository/ReceiptRepository.java
  src/main/java/leets/weeth/domain/account/service/AccountService.java
  src/main/java/leets/weeth/domain/account/service/ReceiptService.java
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
  src/main/java/leets/weeth/global/common/error/CommonExceptionController.java
  src/main/java/leets/weeth/global/common/error/exception/ExceptionType.java
  src/main/java/leets/weeth/global/common/error/exception/custom/AccountExistsException.java
  src/main/java/leets/weeth/global/common/error/exception/custom/AccountNotFoundException.java
  src/main/java/leets/weeth/global/common/error/exception/custom/ReceiptNotFoundException.java
Labels: Feature

#61 #61 Refactor: 출석 API
  src/main/java/leets/weeth/domain/attendance/service/AttendanceService.java
  src/main/java/leets/weeth/domain/user/entity/User.java
Labels: Refactor

#56 #55 Feat: 패널티 기능 구현
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
  src/main/java/leets/weeth/domain/penalty/controller/PenaltyController.java
  src/main/java/leets/weeth/domain/penalty/dto/RequestPenalty.java
  src/main/java/leets/weeth/domain/penalty/dto/ResponsePenalty.java
  src/main/java/leets/weeth/domain/penalty/entity/Penalty.java
  src/main/java/leets/weeth/domain/penalty/repository/PenaltyRepository.java
  src/main/java/leets/weeth/domain/penalty/service/PenaltyService.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/global/common/error/exception/custom/PenaltyNotFoundException.java
Labels: Feature

#64 #62 Feat: 어드민용 회원 조회 + 회원 비번 초기화
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
  src/main/java/leets/weeth/domain/attendance/mapper/AttendanceMapper.java
  src/main/java/leets/weeth/domain/user/controller/UserController.java
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/entity/User.java
  src/main/java/leets/weeth/domain/user/mapper/UserMapper.java
  src/main/java/leets/weeth/domain/user/service/UserService.java
Labels: Feature

#65 #63 Refactor: 회비 사용 내역 기입 로직 중 사진 첨부 로직 수정
  src/main/java/leets/weeth/domain/account/dto/ReceiptDTO.java
  src/main/java/leets/weeth/domain/account/entity/Receipt.java
  src/main/java/leets/weeth/domain/account/mapper/ReceiptMapper.java
  src/main/java/leets/weeth/domain/account/service/ReceiptService.java
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
Labels: Refactor

#67 #66 Refactor: 클라이언트와 소통 시, 학과명 한국어로 수정
  src/main/java/leets/weeth/domain/user/dto/UserDTO.java
  src/main/java/leets/weeth/domain/user/entity/enums/Department.java
  src/main/java/leets/weeth/domain/user/mapper/UserMapper.java
  src/main/java/leets/weeth/global/common/error/exception/custom/DepartmentNotFoundException.java
Labels: Refactor

#68 #63 Refactor: 이미지 응답 로직 수정
  src/main/java/leets/weeth/domain/account/dto/ReceiptDTO.java
  src/main/java/leets/weeth/domain/account/mapper/ReceiptMapper.java
  src/main/java/leets/weeth/domain/account/service/AccountService.java
  src/main/java/leets/weeth/domain/admin/controller/AdminController.java
Labels: Refactor

#70 #69 Chore: 응답 메세지 수정
  src/main/java/leets/weeth/global/auth/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
Labels: Refactor

#76 #75 Feat: 15개씩 게시글 조회하는 기능 추가
  src/main/java/leets/weeth/domain/post/controller/PostController.java
  src/main/java/leets/weeth/domain/post/dto/PostDTO.java
  src/main/java/leets/weeth/domain/post/repository/PostRepository.java
  src/main/java/leets/weeth/domain/post/service/PostService.java
Labels: Feature

#78 #77 Feat: 최근 공지사항 15개 조회 기능
  src/main/java/leets/weeth/domain/event/repository/EventRepository.java
  src/main/java/leets/weeth/domain/notice/controller/NoticeController.java
  src/main/java/leets/weeth/domain/notice/service/NoticeService.java
Labels: Feature

#83 Refactor: 이미지 도메인 로직 수정
  src/main/java/leets/weeth/domain/account/dto/AccountDTO.java
  src/main/java/leets/weeth/domain/account/entity/Receipt.java
  src/main/java/leets/weeth/domain/account/mapper/ReceiptMapper.java
  src/main/java/leets/weeth/domain/account/service/ReceiptService.java
  src/main/java/leets/weeth/domain/event/entity/Event.java
  src/main/java/leets/weeth/domain/file/converter/FileListConverter.java
  src/main/java/leets/weeth/domain/file/entity/File.java
  src/main/java/leets/weeth/domain/file/repository/FileRepository.java
  src/main/java/leets/weeth/domain/file/service/FileService.java
  src/main/java/leets/weeth/domain/notice/dto/ResponseNotice.java
  src/main/java/leets/weeth/domain/notice/mapper/NoticeMapper.java
  src/main/java/leets/weeth/domain/notice/service/NoticeService.java
  src/main/java/leets/weeth/domain/post/dto/ResponsePostDTO.java
  src/main/java/leets/weeth/domain/post/entity/Post.java
  src/main/java/leets/weeth/domain/post/service/PostService.java
  src/main/resources/application-local.yml
Labels: Refactor
